### ISSUE TITLE
> As foto das telas poderia ficar armazenadas no readme apontando o link para o projeto do figma de contribuição

### ISSUE THREAD

**Issue by Rtanxc** [Ryanlucass/ChaveMestra#3]
> As foto das telas poderia ficar armazenadas no readme apontando o link para o projeto do figma de contribuição
Realmente vou fazer isso, fica mais fácil a organização

_Originally posted by @Ryanlucass in https://github.com/Ryanlucass/ChaveMestra/discussions/2#discussioncomment-3727586_

**Comment by Ryanlucass** [comment]
feito
